# Generated by Django 4.2.2 on 2024-08-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_content_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count_reviews',
            field=models.PositiveIntegerField(default=0, verbose_name='Count reviews'),
        ),
        migrations.AddField(
            model_name='book',
            name='sum_rate',
            field=models.PositiveIntegerField(default=0, verbose_name='Sum rete of reviews'),
        ),
    ]
