# Generated by Django 4.2.2 on 2024-08-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_count_reviews_book_sum_rate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['book'], name='books_revie_book_id_68ab4d_idx'),
        ),
    ]
